include: "/config/.gitlab-ci.yml"

publish:npm:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
      when: on_success
    - if: $CI_COMMIT_TAG
      when: manual
  script:
    - npm config set "//registry.npmjs.org/:_authToken=${BOILERPLATE_PUBLISH_NPM_TOKEN}"
    - npm pkg set "repository.url=${BOILERPLATE_PUBLISH_NPM_GIT_URL}"
    - npm publish --access public
