image: node:latest

cache:
  paths:
    - node_modules/
    - dist/

stages:
  - prepare
  - check
  - transform
  - release

npm install:
  stage: prepare
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
  script:
    - for NPM_CONFIG in "${NPM_INSTALL_ADDITIONAL_CONFIG}"; do npm config set "${NPM_CONFIG}"; done
    - npm install

check_commit:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - make check_commit

check_package_json:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - make check_package_json

check_lint:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - make check_lint

check_config:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - make check_config

check_typescript:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - make check_typescript

check_test:
  stage: check
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - make check_test

transform_typescript_clear:
  stage: transform
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - make transform_typescript_clear

tag:prerelease:
  stage: release
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: true
  script:
    - git config user.email "${CI_BOT_EMAIL}"
    - git config user.name "${CI_BOT_NAME}"
    - git remote add gitlab_origin "${CI_BOT_ORIGIN}"
    - npm version prerelease --preid "${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}"
    - git push gitlab_origin --tags

tag:patch:
  stage: release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: true
  script:
    - git config user.email "${CI_BOT_EMAIL}"
    - git config user.name "${CI_BOT_NAME}"
    - git remote add gitlab_origin "${CI_BOT_ORIGIN}"
    - npm version patch
    - git push gitlab_origin "HEAD:${CI_COMMIT_REF_NAME}" --push-option=ci.skip
    - git push gitlab_origin --tags

tag:minor:
  stage: release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: true
  script:
    - git config user.email "${CI_BOT_EMAIL}"
    - git config user.name "${CI_BOT_NAME}"
    - git remote add gitlab_origin "${CI_BOT_ORIGIN}"
    - npm version minor
    - git push gitlab_origin "HEAD:${CI_COMMIT_REF_NAME}" --push-option=ci.skip
    - git push gitlab_origin --tags

tag:major:
  stage: release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: true
  script:
    - git config user.email "${CI_BOT_EMAIL}"
    - git config user.name "${CI_BOT_NAME}"
    - git remote add gitlab_origin "${CI_BOT_ORIGIN}"
    - npm version major
    - git push gitlab_origin "HEAD:${CI_COMMIT_REF_NAME}" --push-option=ci.skip
    - git push gitlab_origin --tags

publish:gitlab:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - npm config set "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}"
    - npm config set "@mrpelz:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
    - npm publish
